# Generated by Django 5.1.4 on 2024-12-20 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pizza',
            new_name='PizzaModel',
        ),
    ]
